hack:
  image: fgrehm/alpine-go-web:1.5.3
  command: bash
  ports:
  - '8080:8080'
  volumes:
  - '.:/code'
  stdin_open: true
  tty: true
  links:
  - mongo

mongo:
  image: 'mongo:3.1.9'
  volumes:
  - './data/mongo:/data/db'

mongoexpress:
  image: 'knickers/mongo-express'
  ports:
  - '8081:8081'
  links:
  - 'mongo'
