hack:
  image: fgrehm/alpine-go-web:1.5.1
  command: bash
  volumes:
  - .:/code
  stdin_open: true
  tty: true
  links:
  - mongo

mongo:
  image: 'mongo:3.1.9'

mongoexpress:
  image: 'knickers/mongo-express'
  ports:
  - '8081:8081'
  links:
  - 'mongo'
